{% set name = "mapyde" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 61075fc0cb8336ee1334372270baa56634ad7e13a075c7397d7511f370959201

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - mapyde = mapyde.cli:app

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling >=0.7
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - typing_extensions >=3.7  # python < 3.8
    - typer
    - tomli # python < 3.11
    - tomli-w
    - jinja2
    - in_place
    - importlib_resources >=1.3.0  # python < 3.9
    - trogon

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - mapyde
  commands:
    - mapyde --version
    - pip check

about:
  home: https://github.com/scipp-atlas/mapyde
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Generation, simulation, analysis, and statistical inference in one go.

  description: >
    MaPyDe stands for MadGraph-Pythia-Delphes which is a utility that allows one to run all of the various HEP toolings or chain them together and perform a quick analysis with the results, such as running CERN ATLAS SimpleAnalysis or pyhf.
  doc_url: https://scipp-atlas.github.io/mapyde/latest/
  dev_url: https://github.com/scipp-atlas/mapyde

extra:
  recipe-maintainers:
    - kratsg
    - mhance
