{% set name = "mapyde" %}
{% set version = "0.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1332a7f23e4a36c9fc19a039371c30a88d2712de7b7188bb4144a3694710cc7a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - mapyde = mapyde.cli:app

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling >=0.7
    - hatch-vcs
  run:
    - python >=3.7
    - typing_extensions >=3.7  # python < 3.8
    - typer
    - toml
    - jinja2
    - in_place
    - importlib_resources >=1.3.0  # python < 3.9

test:
  requires:
    - pip
  imports:
    - mapyde
  commands:
    - mapyde --version
    - pip check

about:
  home: https://github.com/scipp-atlas/mario-mapyde
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Generation, simulation, analysis, and statistical inference in one go.

  description: >
    MaPyDe stands for MadGraph-Pythia-Delphes which is a utility that allows one to run all of the various HEP toolings or chain them together and perform a quick analysis with the results, such as running CERN ATLAS SimpleAnalysis or pyhf.
  doc_url: https://mapyde.readthedocs.io/
  dev_url: https://github.com/scipp-atlas/mario-mapyde

extra:
  recipe-maintainers:
    - kratsg
    - mhance
